/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fsti_ladder_engine_IDBTEngine */

#ifndef _Included_com_fsti_ladder_engine_IDBTEngine
#define _Included_com_fsti_ladder_engine_IDBTEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fsti_ladder_engine_IDBTEngine_IDBT_OK
#define com_fsti_ladder_engine_IDBTEngine_IDBT_OK 0L
#undef com_fsti_ladder_engine_IDBTEngine_IDBT_FAIL
#define com_fsti_ladder_engine_IDBTEngine_IDBT_FAIL -1L
/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getSipRegStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getSipRegStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getNetwrokStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getNetwrokStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getTmLinkStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getTmLinkStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    sendHouseCode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_sendHouseCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    checkImsCallEnable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_checkImsCallEnable
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getImsCallTimeout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getImsCallTimeout
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    cancelCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fsti_ladder_engine_IDBTEngine_cancelCall
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    hangupCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fsti_ladder_engine_IDBTEngine_hangupCall
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    sendOpenDoorPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_sendOpenDoorPassword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getDevInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getDevInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getVersionInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getVersionInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getNetworkInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getNetworkInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getNetworkJoinMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getNetworkJoinMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setNetworkJoinMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setNetworkJoinMethod
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setIPAddress
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setIPAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setNetMask
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setNetMask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setGateway
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setGateway
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setDNS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setDNS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setPPPOEUsername
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setPPPOEUsername
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setPPPOEPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setPPPOEPassword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getPlatformInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getPlatformInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setDevNum
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setDevNum
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setPlatformDomainName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setPlatformDomainName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getSIPInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getSIPInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    getManagementPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fsti_ladder_engine_IDBTEngine_getManagementPassword
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setManagementPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setManagementPassword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setOpendoorPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setOpendoorPassword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    setResetDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_setResetDev
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    createIDBTQue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_createIDBTQue
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    IDBTInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_IDBTInit
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    deleteIDBTQue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_deleteIDBTQue
  (JNIEnv *, jclass);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    listenIDBTState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_listenIDBTState
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fsti_ladder_engine_IDBTEngine
 * Method:    listenIDBTInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fsti_ladder_engine_IDBTEngine_listenIDBTInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
